### ISSUE TITLE
Heads up: updates on mojave require disabling/enabling in security & privacy

### ISSUE THREAD

**Issue by willhoney7** [jaredly/qmoji#11]
On macOS mojave: I can't speak on whether this is universal or just me but every time I update the app (by downloading the new one and replacing qmoji.app in my Applications folder), the app is no longer able to insert emojis. 

I have to go to the System Preferences -> Security & Privacy -> Privacy -> Accessibility -> Uncheck qmoji.app -> Check qmoji.app and it works again.

It may be worth adding a note to the readme about this (if others have this issue as well). I'd be happy to submit a PR regarding this but it would probably be a couple days.

**Comment by arecvlohe** [comment]
I can confirm as well on macOS Mojave 10.14.2
