### ISSUE TITLE
macOS' native emoji picker

### ISSUE THREAD

**Issue by CanRau** [jaredly/qmoji#15]
Hey pretty cool app. Especially showcasing your fluid framework which looks pretty nice 👏

Just had to mention, as no one seems to be mentioning it here that macOS ships in most apps a native emoji picker accessible via `ctrl+cmd+space` 

**edit** just realized it's briefly mentioned in the first sentence of [#future-work](https://github.com/jaredly/qmoji#future-work) 🤣

qmoji seems to be a little bit snappier 🚀 installed just now tho, so am still investigating 😜 

cheers, can be closed, no further action required 👍 

By the way what's the state of fluid?

Update: Hm it's unfortunately not working, the selected emoji won't be inserted into the currently selected text box 🤔 I'm on Mojave

**Comment by CanRau** [comment]
My fault, I missed the [Mojave Note](https://github.com/jaredly/qmoji#mojave-note) in the readme 😅(<- inserted using qmoji)

So it seems actually much quicker and responsive than the native one 👏and even works in the Telegram app where the native one doesn't show up at all 😆

arrow support would be appreciated, but as searching is really quick 🤷‍♂️

**Comment by jaredly** [comment]
I've added a menu item for customizing the shortcut key in the new beta https://github.com/jaredly/qmoji/releases/tag/2.0-beta.2
