### ISSUE TITLE
qmoji not working on Big Sur

### ISSUE THREAD

**Issue by rkorach** [jaredly/qmoji#16]
Hi @jaredly ,
It seems qmoji doesn't work anymore since I updated my MacOS to BigSur.
Interface loads, but whenever I select the emoji, it isn't placed in my text, nothing happens. Can you reproduce on your side?

**Comment by jaredly** [comment]
ooh hm. I don't have BigSur installed, so I can't repro. (I generally wait at least 6 months to install new macos releases because they're often so buggy at first 🙃)
I would guess that BigSur imposes some new privacy restrictions on applications typing into other applications? sorry I can't be more help at the moment

**Comment by rkorach** [comment]
new privacy restrictions was my guess as well.
😞

Le mer. 16 déc. 2020 à 20:47, Jared Forsyth <notifications@github.com> a
écrit :

**Comment by alisonjoseph** [comment]
Also running into this issue after updating to BigSur. Any plans to update? 🙏

**Comment by jaredly** [comment]
yeah sorry about that! I'm still not on big sur, so don't have a great way to diagnose it. I've been thinking of rewriting this project in swift to make contribution easier, as is it's a little hard for people to get up and running.

**Comment by willhoney7** [comment]
Just upgraded to big sur and noticed this. Bummer! This has been my goto for emoji picking for a while now.

**Comment by jaredly** [comment]
Update on this; I'm rewriting qmoji in swift because I'm finally upgrading to big sur 😅

**Comment by sheixt** [comment]
Great news to hear this is being fixed for Big Sur 🥳  Real shame that it's making you have to rewrite it @jaredly 😖  Look forward to it's return
