### ISSUE TITLE
Not inserting the emoji...

### ISSUE THREAD

**Issue by kentcdodds** [jaredly/qmoji#17]
https://user-images.githubusercontent.com/1500684/131159937-044f0d45-13c8-46ed-a46e-bc38024ee71b.mov

**Comment by kentcdodds** [comment]
In that video I'm hitting "Enter" after choosing the emoji I want. Is that wrong? It appears to select the emoji properly because it sets the emoji in my frequently used list, but it doesn't actually insert the emoji.

**Comment by ahmedam55** [comment]
I'm facing the same issue

**Comment by ahmedam55** [comment]
That worked for me!
![image](https://user-images.githubusercontent.com/3703533/151157572-9978a2db-20f9-4080-a045-8b93ac3870da.png)

**Comment by karlhorky** [comment]
@kentcdodds were you able to get it working with the Troubleshooting instructions above? Working for me on macOS Sonoma 14.2

**Comment by karlhorky** [comment]
I opened a PR to make the `Security & Privacy > Privacy > Accessibility` part of the installation instructions, which hopefully will also close this PR:

- #21

**Comment by kentcdodds** [comment]
Yep it's working now. Sorry I never reported back

**Comment by karlhorky** [comment]
np thanks for circling back to it now :)
