### ISSUE TITLE
Support black and white taskbar menu icon

### ISSUE THREAD

**Issue by kentcdodds** [jaredly/qmoji#2]
It's a bit jarring and throws off my aesthetic:

![image](https://user-images.githubusercontent.com/1500684/51853365-5a56bd80-22e5-11e9-86d2-cb8efb6b1384.png)

Would it be possible to not only support a black and white menu icon but also choose which emoji it shows?

**Comment by jaredly** [comment]
ooh that would be fun. I think I'd probably have to bundle a font that had all the emojis in black & white -- If you know of one, let me know!

**Comment by kentcdodds** [comment]
Ah, yeah, that makes sense. Maybe we could get most of the way there if we can select the emoji that shows up. Then I could choose something like ♾ or something :)

**Comment by jaredly** [comment]
![image](https://user-images.githubusercontent.com/112170/51885122-0d9fd080-233f-11e9-9209-5cbc68c06088.png)
ok I got one for ya

**Comment by jaredly** [comment]
fixed in 1.1 https://github.com/jaredly/qmoji/releases/tag/1.1
let me know how it looks! I don't have mojave yet so I can't test dark mode, but I think it should look reasonable 😅

**Comment by kentcdodds** [comment]
Fantastic! Thank you!

**Comment by kentcdodds** [comment]
![image](https://user-images.githubusercontent.com/1500684/51887629-bb1bdf80-2351-11e9-9b7a-8c86c687bb34.png)

Looks good to me!
