### ISSUE TITLE
Learn frequently used emoji

### ISSUE THREAD

**Issue by kentcdodds** [jaredly/qmoji#3]
I'm thinking of something similar to my old library "genie" and it's [Optimistic Anticipation](https://github.com/kentcdodds/genie#about-optimistic-anticipation). It's kinda like how Alfred learns your preferences over time and surfaces up the selections more immediately if you've selected them before.

**Comment by jaredly** [comment]
Yep, I definitely want this too

**Comment by jaredly** [comment]
Fixed in 1.3! https://github.com/jaredly/qmoji/releases/tag/1.3

**Comment by kentcdodds** [comment]
Nice! Thanks!
