### ISSUE TITLE
Support fuzzy matching

### ISSUE THREAD

**Issue by kentcdodds** [jaredly/qmoji#4]
If I mis-type `pray` as `pry` I'd love it to still show up emoji like 🙏

This can be done by using a legit fuzzy matching algorithm, or something simpler and arguably more sensible like what https://github.com/kentcdodds/match-sorter is doing.

**Comment by jaredly** [comment]
Next release will have this :) I implemented it over the weekend

**Comment by jaredly** [comment]
fixed in 1.1 https://github.com/jaredly/qmoji/releases/tag/1.1
