### ISSUE TITLE
Idea/Request: Clicking on emoji with mouse copies to keyboard

### ISSUE THREAD

**Issue by willhoney7** [jaredly/qmoji#5]
The workflow when using the keyboard shortcut to open the menu bar and select an emoji works super well... However it's a little unintuitive when you directly open the menubar with the mouse and select an emoji. You then have to press enter. 

What about making it so clicking on the emoji with the mouse copies it to the clipboard (with a little message indicating that)?

As an alternative/addition: what about double click to do the same functionality as hitting enter?

Thanks, this is great!

**Comment by jaredly** [comment]
Fixed in 1.1 https://github.com/jaredly/qmoji/releases/tag/1.1
thanks for the suggestion! I've switched to select-on-hover, with click meaning "use this emoji".
