### ISSUE TITLE
Allow arrow key selection

### ISSUE THREAD

**Issue by kentcdodds** [jaredly/qmoji#6]
Currently you can select emoji via the <kbd>Tab</kbd> key, but I think it'd be nice to use the arrow keys as well so I can use up and down to navigate around the options.

**Comment by jaredly** [comment]
Yeah, I was on the fence about that -- because left & right arrow keys could be used to navigate within the text box. But I think it's probably the right choice

**Comment by jaredly** [comment]
I've added this in the new 2.0 beta! https://github.com/jaredly/qmoji/releases/tag/2.0-beta.2

**Comment by kentcdodds** [comment]
Oh hooray! I can't wait to try it 😁
