### ISSUE TITLE
Request: Ability to Quit

### ISSUE THREAD

**Issue by willhoney7** [jaredly/qmoji#8]
As I was updating to 1.1 I realized how difficult it was to quit the app! I had to open activity monitor and forcequit it. Is there an easier way? If not, can that be added?

Thanks for this app! It's great.

**Comment by jaredly** [comment]
Sorry about that 😅 if you open the window by clicking on the icon, and them press `cmd+q` it will quit the app. I'm planning to add a settings pane for configuration, that would also work for quitting I imagine

**Comment by jaredly** [comment]
Fixed in 1.2!
