### ISSUE TITLE
Does not work with macOS Sierra

### ISSUE THREAD

**Issue by btbytes** [jaredly/qmoji#9]
some of us are stuck on using "supported versions" of macOS. Is it possible to release a version that works on older versions like Sierra?

Thank you.

**Comment by jaredly** [comment]
hrmm yeah I'd love to support it, not totally sure what's involved. I develop on High Sierra.

**Comment by karlhorky** [comment]
It seems this is outdated? (maybe it can be closed) qmoji works on macOS Sonoma 14.2
